---
title: "Teng_2015"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


# Libraries
```{r}
library(dplyr)
library(stringr)
library(tibble)
library(MatrixGenerics)
```


# out_dir
```{r}
out_dir = "/home/wasif/Rproj_221101_Plaque_Genus_Species_metaanalysis"
```

# Import Teng_2015
```{r}
Teng_2015_qiime_table = read.csv("/home/storage2/wasif/Plaque_metagenome_meta_analysis/Teng_2015_plaque/Teng_2015_try_for_sample_subset_250222/Teng_2015_samples_with_3000_reads/Teng_2015_level-7.csv", check.names = F)
Teng_2015_qiime_table 

Teng_2015_qiime_table  = Teng_2015_qiime_table %>% 
  column_to_rownames("index")
Teng_2015_qiime_table

Teng_2015_otu = Teng_2015_qiime_table  %>% 
  dplyr::select(-c(Disease_status,	Host_age,	Host_sex,	Sample_type,	Geo_location,	Study_name))
Teng_2015_otu

Teng_2015_meta = Teng_2015_qiime_table  %>% 
  dplyr::select(c(Disease_status,	Host_age,	Host_sex,	Sample_type,	Geo_location,	Study_name))
Teng_2015_meta
```
# RA and filter OTU table
```{r}
Teng_2015_otu_sp = Teng_2015_otu %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("OTUs")
Teng_2015_otu_sp

Teng_2015_otu_sp = Teng_2015_otu_sp %>% 
  filter(str_detect(OTUs, "s__")) %>% 
  mutate()
Teng_2015_otu_sp

Teng_2015_otu_sp = Teng_2015_otu_sp %>% 
  mutate(OTUs = str_replace(OTUs, ".*s__", ""))
Teng_2015_otu_sp

Teng_2015_otu_sp = Teng_2015_otu_sp %>% 
  column_to_rownames("OTUs") %>% 
  as.matrix() %>% 
  #prop.table(2) %>% 
  as.data.frame() 
Teng_2015_otu_sp
```

```{r}
# otu_table_mtx = as.matrix(Teng_2015_otu_sp)
# a_f.max <- rowMaxs(otu_table_mtx)/rowSums(otu_table_mtx)
# which_1 = which(a_f.max >= 0.00001)
# 
# a_f.max_2 <- rowMaxs(otu_table_mtx/rowSums(otu_table_mtx) )
# which_2 = which(a_f.max_2 >= 0.00001)
# 
# setequal(which_1 , which_2)
```

# function for abundance and prevalence 
```{r}
# otu table with samples as rownames in #for details see siamcat filter funcion
#abundance cut off if less than this in all the samples
abundance_prevelance_filter_function = function(otu_table,
                                                a_cut_off = 0.00001, #abundance cut off
                                                p_cut_off = 0.05 # prevalence cut off
                                                ) { 
  #abundance filter
  otu_table_mtx = as.matrix(otu_table)
# a_f.max <- rowMaxs(otu_table_mtx)
  a_f.max <- rowMaxs(otu_table_mtx)/rowSums(otu_table_mtx)
  a_f.idx <- which(a_f.max >= a_cut_off)
  a_f.names <- rownames(otu_table_mtx)[a_f.idx]
  a_filt.feat=otu_table_mtx[a_f.names,]
  
  # prevalance filter
  p_f.idx <- which(rowSums(a_filt.feat > 0) / ncol(a_filt.feat) > p_cut_off)
  p_f.names <- rownames(a_filt.feat)[p_f.idx]
  p_filt.feat=a_filt.feat[p_f.names,]
  p_filt.feat_df = as.data.frame(p_filt.feat)
  return(p_filt.feat_df)
                                                }
```

# Apply prevalence filter function
```{r}
Teng_2015_otu_sp_filt = abundance_prevelance_filter_function(Teng_2015_otu_sp)
 Teng_2015_otu_sp_filt
```

# import Teng_2015 level_6
```{r}
Teng_2015_qiime_table_level_6 = read.csv("/home/storage2/wasif/Plaque_metagenome_meta_analysis/Teng_2015_plaque/Teng_2015_try_for_sample_subset_250222/Teng_2015_samples_with_3000_reads/Teng_2015_level-6.csv", check.names = F)
Teng_2015_qiime_table_level_6 

Teng_2015_qiime_table_level_6  = Teng_2015_qiime_table_level_6 %>% 
  column_to_rownames("index")
Teng_2015_qiime_table_level_6

Teng_2015_otu_level_6 = Teng_2015_qiime_table_level_6  %>% 
  dplyr::select(-c(Disease_status,	Host_age,	Host_sex,	Sample_type,	Geo_location,	Study_name))
Teng_2015_otu_level_6

```

# RA and filter OTU table
```{r}
Teng_2015_otu_gn = Teng_2015_otu_level_6 %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("OTUs")
Teng_2015_otu_gn

Teng_2015_otu_gn = Teng_2015_otu_gn %>% 
  filter(str_detect(OTUs, "g__")) %>% 
  mutate()
Teng_2015_otu_gn

Teng_2015_otu_gn = Teng_2015_otu_gn %>% 
  mutate(OTUs = str_replace(OTUs, ".*g__", ""))
Teng_2015_otu_gn

Teng_2015_otu_gn = Teng_2015_otu_gn %>% 
  column_to_rownames("OTUs") %>% 
  as.matrix() %>% 
  #prop.table(2) %>% 
  as.data.frame() 
Teng_2015_otu_gn
```
# Apply prevalence filter function
```{r}
Teng_2015_otu_gn_filt = abundance_prevelance_filter_function(Teng_2015_otu_gn)
 Teng_2015_otu_gn_filt
```

# make a list containing otu and meta 
```{r}
Teng_2015_otu_sp_filt
Teng_2015_meta
Teng_2015_otu_gn_filt
Teng_2015_otu_meta_rdata = list(Teng_2015_otu_sp_filt, Teng_2015_meta, Teng_2015_otu_gn_filt)
save(Teng_2015_otu_meta_rdata, file=paste0(out_dir, "/Teng_2015_otu_meta_rdata.RData"))
```