---
title: "try with mikropml"
output: html_document
date: '2022-11-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
rm(list = ls())
set.seed(23456)
```

# To print the start time
```{r}
start_time = Sys.time()
start_time
```

# ggplot titles and other parameters
```{r}
ml_method = "randomForest"
param_set = NULL
# ml_method = "enet"
# param_set = list('alpha'=0) # 0 is for ridge and 1 is for lasso

top_feat_num_c = c(5, 10, 15, 20, 30, 50, 75, 100)#, 100, 120)
num_resample = 3

ggplot_title = paste0("Pooled_Pl_Species_RA_CLR_sPLSDA", "_", ml_method) 
```

# Libraries

```{r}
library(dplyr)
library(tibble)
library(ggplot2)
library(DT)
library(stringr)
library(pROC) #ggroc
library(ranger)
library(SIAMCAT)
library(mikropml)
library(progressr)
handlers(global = TRUE)
# library(PCAtools) # for the command PCAtools::pca
# library(mixOmics)
# library(phyloseq)
# library(microbiome)
# library(PLSDAbatch)
# library(vegan) #varpart
```

# To print the start time
```{r}
start_time = Sys.time()
start_time
```

# for parallelization registeration
```{r}
library(foreach)
library(doParallel)

doFuture::registerDoFuture()
future::plan(future::multisession, workers = 5)
```

```{r}
in_dir  = "../../Plaque_Species/Species_221101_2_processed_data_files"
#out_dir = "/home/wasif/Rproj_221101_Plaque_Genus_Species_metaanalysis/Plaque_Species/Species_221101_2_processed_data_files"
```

# Import data

```{r}
Pooled_Pl_Species_RA_table = read.table(paste0(in_dir, "/Plaque_Species_relative_abundance_OTU_table_with_meta_data.txt"),
                                   header = T,
                                   sep = "\t",
                                  check.names = F )
Pooled_Pl_Species_RA_table
```

# separate OTU and metadata

```{r}
# Meta
Pooled_Pl_Species_meta = Pooled_Pl_Species_RA_table %>% 
  column_to_rownames("sampleid") %>% 
  dplyr::select(c(Disease_status ,Host_age, Host_sex, Sample_type, Geo_location, Study_name))
Pooled_Pl_Species_meta

# OTU
Pooled_Pl_Species_RA = Pooled_Pl_Species_RA_table %>% 
  column_to_rownames("sampleid") %>% 
  dplyr::select(!c(Disease_status ,Host_age, Host_sex, Sample_type, Geo_location, Study_name)) 
Pooled_Pl_Species_RA

# Pooled_Pl_Species_RA_t =  Pooled_Pl_Species_RA %>% 
#   t() %>% 
#   as.data.frame()
# Pooled_Pl_Species_RA_t
```
# rename OTU and meta tables
```{r}
Pooled_otu = Pooled_Pl_Species_RA # taxa should be rows
Pooled_otu
Pooled_meta = Pooled_Pl_Species_meta # rownames should be ids
Pooled_meta
```

# Prepare data for mikropml
```{r}
Pooled_meta_otu  = merge(Pooled_Pl_Species_meta[,1, drop=FALSE], Pooled_otu, by = "row.names") %>% column_to_rownames("Row.names")
Pooled_meta_otu
```


```{r}
# results <- run_ml(Pooled_meta_otu,
#                   'glmnet',
#                   find_feature_importance = F, 
#                   outcome_colname = 'Disease_status',
#                   training_frac = 0.99,
#                   seed = 2019,
#                   )
# results$performance
```


```{r}
#get_feature_importance(results)
```

# To print the start time
```{r}
start_time = Sys.time()
start_time

time_taken_till_here = function(){ 
  return(difftime(Sys.time(), start_time) ) # needs only start time, end time can be taken from Sys.time() so no need to assign
}
```


```{r}
param_grid <- expand.grid( seeds = seq(100, 104),
                           methods = c('glmnet', 'rf' , "rpart2", "svmRadial", "xgbTree")
)
```


```{r}
results_mtx <- future.apply::future_mapply(
    function(seed,method) {
      run_ml(Pooled_meta_otu, outcome_colname = 'Disease_status', training_frac = 0.8, method, cv_times = 5, seed = seed)
      },
    param_grid$seeds,
    param_grid$methods %>% as.character(),
    future.seed = TRUE
  )
```

```{r}
perf_df <- lapply(results_mtx['performance',], 
                   function(x) {
                     x %>% dplyr::select(cv_metric_AUC, AUC, method)
                   }) %>% 
  dplyr::bind_rows()
perf_df

perf_boxplot <- plot_model_performance(perf_df) +
  ggtitle("Cross-validation and Test-set validation at Species level") +
  ylim(0.5, 1.0) +
  #scale_y_continuous(breaks=c(0, .20, .40, .60, .80, 1.0), limits = c(0, 1)) +
  scale_x_discrete(labels=c("glmnet" = "Logistic regression",
                            "rf" = "Random forest",
                              "rpart2" = "Decision tree",
                            "svmRadial" =  "SVM radial",
                            "xgbTree" = "XGBoost")) +
    theme_bw() +
  theme(axis.text.x = element_text( size=10, angle=45, hjust = 1, vjust = 1) )

perf_boxplot
```

```{r}
time_taken_till_here()
```


```{r}
# 
# results_mtx2 <- future.apply::future_mapply(
#     function(seed,method) {
#       run_ml(Pooled_meta_otu, outcome_colname = 'Disease_status', training_frac = 0.99, method, cv_times = 5,seed = seed)
#       },
#     param_grid$seeds,
#     param_grid$methods %>% as.character(),
#     future.seed = TRUE
#   )
```

```{r}
# perf_df2 <- lapply(results_mtx2['performance',], 
#                    function(x) {
#                      x %>% select(cv_metric_AUC, AUC, method)
#                    }) %>% 
#   dplyr::bind_rows()
# perf_df2
# 
# perf_boxplot2 <- plot_model_performance(perf_df2) +
#   ggtitle("Cross Validation at Species level") +
#   scale_y_continuous(breaks=c(0, .20, .40, .60, .80, 1.0), limits = c(0, 1))
# perf_boxplot2
```
```{r}
time_taken_till_here()
```

#stop cluster

```{r}
future::plan(future::multisession)
#stopCluster(cl)
stopImplicitCluster()
```



